# This rule is not used by the project prometheusflux itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over chaos.shanto.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prometheusflux
    app.kubernetes.io/managed-by: kustomize
  name: chaosexperiment-admin-role
rules:
- apiGroups:
  - chaos.shanto.dev
  resources:
  - chaosexperiments
  verbs:
  - '*'
- apiGroups:
  - chaos.shanto.dev
  resources:
  - chaosexperiments/status
  verbs:
  - get
