apiVersion: chaos.shanto.dev/v1alpha1
kind: ChaosExperiment
metadata:
  labels:
    app.kubernetes.io/name: prometheusflux
    app.kubernetes.io/managed-by: kustomize
  name: chaosexperiment-sample
spec:
  # TODO(user): Add fields here
